# Generated by Django 2.2.10 on 2020-03-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_peces', '0002_pedidos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
    ]
